/**
 * Emoji database — 200+ emojis organized by category.
 * Used by the EmojiPicker (sticker-style) component.
 *
 * Categories match WhatsApp/Telegram convention + kid-friendly extras.
 */

export interface EmojiEntry {
  emoji: string;
  label: string;
  /** Twemoji CDN codepoint (for image fallback) */
  codepoint?: string;
  /** Search keywords — lowercase space-separated */
  keywords: string;
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;       // tab icon emoji
  emojis: EmojiEntry[];
}

// ══════════════════════════════════════════════════════════════════
// ANIMALS
// ══════════════════════════════════════════════════════════════════

const ANIMALS: EmojiEntry[] = [
  { emoji: '🐶', label: 'Dog', codepoint: '1f436', keywords: 'dog puppy pet animal' },
  { emoji: '🐱', label: 'Cat', codepoint: '1f431', keywords: 'cat kitten pet animal' },
  { emoji: '🐭', label: 'Mouse', codepoint: '1f42d', keywords: 'mouse rat animal' },
  { emoji: '🐹', label: 'Hamster', codepoint: '1f439', keywords: 'hamster pet animal' },
  { emoji: '🐰', label: 'Rabbit', codepoint: '1f430', keywords: 'rabbit bunny pet animal' },
  { emoji: '🦊', label: 'Fox', codepoint: '1f98a', keywords: 'fox animal wild' },
  { emoji: '🐻', label: 'Bear', codepoint: '1f43b', keywords: 'bear animal' },
  { emoji: '🐼', label: 'Panda', codepoint: '1f43c', keywords: 'panda bear animal' },
  { emoji: '🐨', label: 'Koala', codepoint: '1f428', keywords: 'koala animal' },
  { emoji: '🐯', label: 'Tiger', codepoint: '1f42f', keywords: 'tiger cat animal' },
  { emoji: '🦁', label: 'Lion', codepoint: '1f981', keywords: 'lion king animal' },
  { emoji: '🐮', label: 'Cow', codepoint: '1f42e', keywords: 'cow cattle farm animal' },
  { emoji: '🐷', label: 'Pig', codepoint: '1f437', keywords: 'pig piggy farm animal' },
  { emoji: '🐸', label: 'Frog', codepoint: '1f438', keywords: 'frog toad animal' },
  { emoji: '🐵', label: 'Monkey', codepoint: '1f435', keywords: 'monkey ape primate animal' },
  { emoji: '🐔', label: 'Chicken', codepoint: '1f414', keywords: 'chicken hen poultry farm animal' },
  { emoji: '🐧', label: 'Penguin', codepoint: '1f427', keywords: 'penguin bird animal' },
  { emoji: '🐦', label: 'Bird', codepoint: '1f426', keywords: 'bird animal' },
  { emoji: '🐤', label: 'Baby Chick', codepoint: '1f424', keywords: 'chick baby bird animal' },
  { emoji: '🦆', label: 'Duck', codepoint: '1f986', keywords: 'duck bird animal' },
  { emoji: '🦅', label: 'Eagle', codepoint: '1f985', keywords: 'eagle bird animal' },
  { emoji: '🦉', label: 'Owl', codepoint: '1f989', keywords: 'owl bird animal wise' },
  { emoji: '🦇', label: 'Bat', codepoint: '1f987', keywords: 'bat animal' },
  { emoji: '🐺', label: 'Wolf', codepoint: '1f43a', keywords: 'wolf animal' },
  { emoji: '🐗', label: 'Boar', codepoint: '1f417', keywords: 'boar pig animal' },
  { emoji: '🐴', label: 'Horse', codepoint: '1f434', keywords: 'horse pony farm animal' },
  { emoji: '🦄', label: 'Unicorn', codepoint: '1f984', keywords: 'unicorn magical animal' },
  { emoji: '🐝', label: 'Bee', codepoint: '1f41d', keywords: 'bee honey insect animal' },
  { emoji: '🪱', label: 'Worm', codepoint: '1fab1', keywords: 'worm animal' },
  { emoji: '🐛', label: 'Bug', codepoint: '1f41b', keywords: 'bug caterpillar insect animal' },
  { emoji: '🦋', label: 'Butterfly', codepoint: '1f98b', keywords: 'butterfly insect animal' },
  { emoji: '🐌', label: 'Snail', codepoint: '1f40c', keywords: 'snail animal' },
  { emoji: '🐞', label: 'Ladybug', codepoint: '1f41e', keywords: 'ladybug beetle insect animal' },
  { emoji: '🐜', label: 'Ant', codepoint: '1f41c', keywords: 'ant insect animal' },
  { emoji: '🪲', label: 'Beetle', codepoint: '1fab2', keywords: 'beetle insect animal' },
  { emoji: '🐢', label: 'Turtle', codepoint: '1f422', keywords: 'turtle tortoise animal' },
  { emoji: '🐍', label: 'Snake', codepoint: '1f40d', keywords: 'snake reptile animal' },
  { emoji: '🦎', label: 'Lizard', codepoint: '1f98e', keywords: 'lizard reptile animal' },
  { emoji: '🐊', label: 'Crocodile', codepoint: '1f40a', keywords: 'crocodile alligator animal' },
  { emoji: '🦕', label: 'Sauropod', codepoint: '1f995', keywords: 'dinosaur animal' },
  { emoji: '🦖', label: 'T-Rex', codepoint: '1f996', keywords: 'dinosaur t-rex animal' },
  { emoji: '🐳', label: 'Whale', codepoint: '1f433', keywords: 'whale animal ocean' },
  { emoji: '🐬', label: 'Dolphin', codepoint: '1f42c', keywords: 'dolphin animal ocean' },
  { emoji: '🦈', label: 'Shark', codepoint: '1f988', keywords: 'shark animal ocean' },
  { emoji: '🐟', label: 'Fish', codepoint: '1f41f', keywords: 'fish animal ocean' },
  { emoji: '🐠', label: 'Tropical Fish', codepoint: '1f420', keywords: 'tropical fish animal ocean' },
  { emoji: '🐡', label: 'Blowfish', codepoint: '1f421', keywords: 'blowfish pufferfish animal ocean' },
  { emoji: '🦭', label: 'Seal', codepoint: '1f9ad', keywords: 'seal animal ocean' },
  { emoji: '🐙', label: 'Octopus', codepoint: '1f419', keywords: 'octopus animal ocean' },
  { emoji: '🦑', label: 'Squid', codepoint: '1f991', keywords: 'squid animal ocean' },
  { emoji: '🦧', label: 'Orangutan', codepoint: '1f9a7', keywords: 'orangutan monkey animal' },
  { emoji: '🐘', label: 'Elephant', codepoint: '1f418', keywords: 'elephant animal' },
  { emoji: '🦛', label: 'Hippopotamus', codepoint: '1f99b', keywords: 'hippo animal' },
  { emoji: '🦏', label: 'Rhinoceros', codepoint: '1f98f', keywords: 'rhino animal' },
  { emoji: '🐪', label: 'Camel', codepoint: '1f42a', keywords: 'camel animal' },
  { emoji: '🐫', label: 'Two-Hump Camel', codepoint: '1f42b', keywords: 'camel animal' },
  { emoji: '🦒', label: 'Giraffe', codepoint: '1f992', keywords: 'giraffe animal' },
  { emoji: '🦓', label: 'Zebra', codepoint: '1f993', keywords: 'zebra animal' },
  { emoji: '🦘', label: 'Kangaroo', codepoint: '1f998', keywords: 'kangaroo animal' },
  { emoji: '🦥', label: 'Sloth', codepoint: '1f9a5', keywords: 'sloth animal' },
  { emoji: '🦦', label: 'Otter', codepoint: '1f9a6', keywords: 'otter animal' },
  { emoji: '🦫', label: 'Beaver', codepoint: '1f9ab', keywords: 'beaver animal' },
  { emoji: '🐾', label: 'Paw Prints', codepoint: '1f43e', keywords: 'paw prints animal' },
  { emoji: '🦜', label: 'Parrot', codepoint: '1f99c', keywords: 'parrot bird animal' },
  { emoji: '🦩', label: 'Flamingo', codepoint: '1f9a9', keywords: 'flamingo bird animal' },
  { emoji: '🦚', label: 'Peacock', codepoint: '1f99a', keywords: 'peacock bird animal' },
  { emoji: '🦤', label: 'Dodo', codepoint: '1f9a4', keywords: 'dodo bird animal' },
  { emoji: '🪶', label: 'Feather', codepoint: '1fab6', keywords: 'feather bird' },
  { emoji: '🐾', label: 'Paws', codepoint: '1f43e', keywords: 'paws paw animal' },
];

// ══════════════════════════════════════════════════════════════════
// FOOD & DRINK
// ══════════════════════════════════════════════════════════════════

const FOOD: EmojiEntry[] = [
  { emoji: '🍎', label: 'Apple', codepoint: '1f34e', keywords: 'apple fruit red' },
  { emoji: '🍐', label: 'Pear', codepoint: '1f350', keywords: 'pear fruit green' },
  { emoji: '🍊', label: 'Orange', codepoint: '1f34a', keywords: 'orange fruit citrus' },
  { emoji: '🍋', label: 'Lemon', codepoint: '1f34b', keywords: 'lemon fruit citrus yellow' },
  { emoji: '🍌', label: 'Banana', codepoint: '1f34c', keywords: 'banana fruit yellow' },
  { emoji: '🍉', label: 'Watermelon', codepoint: '1f349', keywords: 'watermelon fruit' },
  { emoji: '🍇', label: 'Grapes', codepoint: '1f347', keywords: 'grapes fruit purple' },
  { emoji: '🍓', label: 'Strawberry', codepoint: '1f353', keywords: 'strawberry fruit red' },
  { emoji: '🫐', label: 'Blueberries', codepoint: '1fad0', keywords: 'blueberry fruit blue' },
  { emoji: '🍈', label: 'Melon', codepoint: '1f348', keywords: 'melon fruit' },
  { emoji: '🍒', label: 'Cherries', codepoint: '1f352', keywords: 'cherry fruit red' },
  { emoji: '🍑', label: 'Peach', codepoint: '1f351', keywords: 'peach fruit' },
  { emoji: '🥭', label: 'Mango', codepoint: '1f96d', keywords: 'mango fruit tropical' },
  { emoji: '🍍', label: 'Pineapple', codepoint: '1f34d', keywords: 'pineapple fruit tropical' },
  { emoji: '🥥', label: 'Coconut', codepoint: '1f965', keywords: 'coconut fruit' },
  { emoji: '🥝', label: 'Kiwi', codepoint: '1f95d', keywords: 'kiwi fruit green' },
  { emoji: '🍅', label: 'Tomato', codepoint: '1f345', keywords: 'tomato vegetable red' },
  { emoji: '🥕', label: 'Carrot', codepoint: '1f955', keywords: 'carrot vegetable orange' },
  { emoji: '🌽', label: 'Corn', codepoint: '1f33d', keywords: 'corn maize vegetable yellow' },
  { emoji: '🥦', label: 'Broccoli', codepoint: '1f966', keywords: 'broccoli vegetable green' },
  { emoji: '🥬', label: 'Leafy Green', codepoint: '1f96c', keywords: 'lettuce green vegetable' },
  { emoji: '🥒', label: 'Cucumber', codepoint: '1f952', keywords: 'cucumber vegetable green' },
  { emoji: '🌶️', label: 'Chili', codepoint: '1f336', keywords: 'chili pepper hot red' },
  { emoji: '🫑', label: 'Bell Pepper', codepoint: '1fad1', keywords: 'bell pepper vegetable' },
  { emoji: '🥔', label: 'Potato', codepoint: '1f954', keywords: 'potato vegetable' },
  { emoji: '🍠', label: 'Sweet Potato', codepoint: '1f360', keywords: 'sweet potato vegetable' },
  { emoji: '🧅', label: 'Onion', codepoint: '1f9c5', keywords: 'onion vegetable' },
  { emoji: '🧄', label: 'Garlic', codepoint: '1f9c4', keywords: 'garlic vegetable' },
  { emoji: '🍆', label: 'Eggplant', codepoint: '1f346', keywords: 'eggplant aubergine purple vegetable' },
  { emoji: '🥑', label: 'Avocado', codepoint: '1f951', keywords: 'avocado fruit green' },
  { emoji: '🍞', label: 'Bread', codepoint: '1f35e', keywords: 'bread food' },
  { emoji: '🥖', label: 'Baguette', codepoint: '1f956', keywords: 'baguette bread food' },
  { emoji: '🧀', label: 'Cheese', codepoint: '1f9c0', keywords: 'cheese food yellow' },
  { emoji: '🥚', label: 'Egg', codepoint: '1f95a', keywords: 'egg food' },
  { emoji: '🍳', label: 'Cooking', codepoint: '1f373', keywords: 'egg cooking food' },
  { emoji: '🥞', label: 'Pancakes', codepoint: '1f95e', keywords: 'pancake food breakfast' },
  { emoji: '🧇', label: 'Waffle', codepoint: '1f9c7', keywords: 'waffle food breakfast' },
  { emoji: '🥓', label: 'Bacon', codepoint: '1f953', keywords: 'bacon meat food' },
  { emoji: '🍗', label: 'Drumstick', codepoint: '1f357', keywords: 'chicken leg drumstick food' },
  { emoji: '🍖', label: 'Meat', codepoint: '1f356', keywords: 'meat food' },
  { emoji: '🥩', label: 'Steak', codepoint: '1f969', keywords: 'steak meat food' },
  { emoji: '🍕', label: 'Pizza', codepoint: '1f355', keywords: 'pizza food' },
  { emoji: '🌭', label: 'Hot Dog', codepoint: '1f32d', keywords: 'hot dog food' },
  { emoji: '🍔', label: 'Hamburger', codepoint: '1f354', keywords: 'hamburger burger food' },
  { emoji: '🍟', label: 'French Fries', codepoint: '1f35f', keywords: 'fries french fries food' },
  { emoji: '🍿', label: 'Popcorn', codepoint: '1f37f', keywords: 'popcorn food snack' },
  { emoji: '🥗', label: 'Salad', codepoint: '1f957', keywords: 'salad food green' },
  { emoji: '🍜', label: 'Ramen', codepoint: '1f35c', keywords: 'ramen noodles food' },
  { emoji: '🍝', label: 'Spaghetti', codepoint: '1f35d', keywords: 'spaghetti pasta food' },
  { emoji: '🍣', label: 'Sushi', codepoint: '1f363', keywords: 'sushi food japanese' },
  { emoji: '🍦', label: 'Ice Cream', codepoint: '1f366', keywords: 'ice cream dessert food' },
  { emoji: '🍩', label: 'Donut', codepoint: '1f369', keywords: 'donut dessert food' },
  { emoji: '🍪', label: 'Cookie', codepoint: '1f36a', keywords: 'cookie dessert food' },
  { emoji: '🎂', label: 'Birthday Cake', codepoint: '1f382', keywords: 'cake birthday dessert food' },
  { emoji: '🍰', label: 'Shortcake', codepoint: '1f370', keywords: 'cake dessert food' },
  { emoji: '🧁', label: 'Cupcake', codepoint: '1f9c1', keywords: 'cupcake dessert food' },
  { emoji: '🍫', label: 'Chocolate', codepoint: '1f36b', keywords: 'chocolate candy dessert' },
  { emoji: '🍬', label: 'Candy', codepoint: '1f36c', keywords: 'candy sweet food' },
  { emoji: '🍭', label: 'Lollipop', codepoint: '1f36d', keywords: 'lollipop candy sweet food' },
  { emoji: '🥤', label: 'Cup with Straw', codepoint: '1f964', keywords: 'juice drink cup' },
  { emoji: '🥛', label: 'Milk', codepoint: '1f95b', keywords: 'milk drink' },
  { emoji: '☕', label: 'Coffee', codepoint: '2615', keywords: 'coffee tea drink hot' },
  { emoji: '🍵', label: 'Tea', codepoint: '1f375', keywords: 'tea cup drink' },
  { emoji: '🧃', label: 'Juice Box', codepoint: '1f9c3', keywords: 'juice box drink' },
  { emoji: '🫗', label: 'Pouring Drink', codepoint: '1fad7', keywords: 'pouring drink water' },
];

// ══════════════════════════════════════════════════════════════════
// SHAPES & SYMBOLS
// ══════════════════════════════════════════════════════════════════

const SHAPES: EmojiEntry[] = [
  { emoji: '⭐', label: 'Star', codepoint: '2b50', keywords: 'star shape yellow' },
  { emoji: '🌟', label: 'Glowing Star', codepoint: '1f31f', keywords: 'star glow shape' },
  { emoji: '💫', label: 'Dizzy Star', codepoint: '1f4ab', keywords: 'star dizzy shape' },
  { emoji: '✨', label: 'Sparkles', codepoint: '2728', keywords: 'sparkle shape shine' },
  { emoji: '⚡', label: 'Lightning', codepoint: '26a1', keywords: 'lightning thunderbolt shape' },
  { emoji: '🔥', label: 'Fire', codepoint: '1f525', keywords: 'fire flame hot shape' },
  { emoji: '❤️', label: 'Heart', codepoint: '2764', keywords: 'heart love shape red' },
  { emoji: '🧡', label: 'Orange Heart', codepoint: '1f9e1', keywords: 'heart orange love shape' },
  { emoji: '💛', label: 'Yellow Heart', codepoint: '1f49b', keywords: 'heart yellow love shape' },
  { emoji: '💚', label: 'Green Heart', codepoint: '1f49a', keywords: 'heart green love shape' },
  { emoji: '💙', label: 'Blue Heart', codepoint: '1f499', keywords: 'heart blue love shape' },
  { emoji: '💜', label: 'Purple Heart', codepoint: '1f49c', keywords: 'heart purple love shape' },
  { emoji: '🖤', label: 'Black Heart', codepoint: '1f5a4', keywords: 'heart black shape' },
  { emoji: '🤍', label: 'White Heart', codepoint: '1f90d', keywords: 'heart white shape' },
  { emoji: '💕', label: 'Two Hearts', codepoint: '1f495', keywords: 'hearts love shape' },
  { emoji: '💖', label: 'Sparkling Heart', codepoint: '1f496', keywords: 'heart sparkle love shape' },
  { emoji: '💗', label: 'Growing Heart', codepoint: '1f497', keywords: 'heart growing love shape' },
  { emoji: '💘', label: 'Heart Arrow', codepoint: '1f498', keywords: 'heart arrow love shape' },
  { emoji: '💝', label: 'Gift Heart', codepoint: '1f49d', keywords: 'heart gift love shape' },
  { emoji: '⭕', label: 'Circle', codepoint: '2b55', keywords: 'circle shape red' },
  { emoji: '⬜', label: 'White Square', codepoint: '2b1c', keywords: 'square shape white' },
  { emoji: '⬛', label: 'Black Square', codepoint: '2b1b', keywords: 'square shape black' },
  { emoji: '🔴', label: 'Red Circle', codepoint: '1f534', keywords: 'circle red shape' },
  { emoji: '🟠', label: 'Orange Circle', codepoint: '1f7e0', keywords: 'circle orange shape' },
  { emoji: '🟡', label: 'Yellow Circle', codepoint: '1f7e1', keywords: 'circle yellow shape' },
  { emoji: '🟢', label: 'Green Circle', codepoint: '1f7e2', keywords: 'circle green shape' },
  { emoji: '🔵', label: 'Blue Circle', codepoint: '1f535', keywords: 'circle blue shape' },
  { emoji: '🟣', label: 'Purple Circle', codepoint: '1f7e3', keywords: 'circle purple shape' },
  { emoji: '🔺', label: 'Red Triangle', codepoint: '1f53a', keywords: 'triangle shape red' },
  { emoji: '🔻', label: 'Down Triangle', codepoint: '1f53b', keywords: 'triangle shape down' },
  { emoji: '💎', label: 'Diamond', codepoint: '1f48e', keywords: 'diamond gem shape blue' },
  { emoji: '💠', label: 'Diamond Shape', codepoint: '1f4a0', keywords: 'diamond shape' },
  { emoji: '🌙', label: 'Crescent Moon', codepoint: '1f319', keywords: 'moon crescent night shape' },
  { emoji: '☀️', label: 'Sun', codepoint: '2600', keywords: 'sun shape bright' },
  { emoji: '🌤️', label: 'Sun Behind Cloud', codepoint: '1f324', keywords: 'sun cloud weather' },
  { emoji: '🌈', label: 'Rainbow', codepoint: '1f308', keywords: 'rainbow shape color' },
  { emoji: '☁️', label: 'Cloud', codepoint: '2601', keywords: 'cloud weather shape white' },
  { emoji: '❄️', label: 'Snowflake', codepoint: '2744', keywords: 'snowflake cold winter shape' },
  { emoji: '💧', label: 'Droplet', codepoint: '1f4a7', keywords: 'water drop shape blue' },
  { emoji: '🫧', label: 'Bubbles', codepoint: '1fae7', keywords: 'bubbles shape' },
];

// ══════════════════════════════════════════════════════════════════
// NUMBERS
// ══════════════════════════════════════════════════════════════════

const NUMBERS: EmojiEntry[] = [
  { emoji: '0️⃣', label: 'Zero', codepoint: '30-20e3', keywords: '0 zero number' },
  { emoji: '1️⃣', label: 'One', codepoint: '31-20e3', keywords: '1 one number' },
  { emoji: '2️⃣', label: 'Two', codepoint: '32-20e3', keywords: '2 two number' },
  { emoji: '3️⃣', label: 'Three', codepoint: '33-20e3', keywords: '3 three number' },
  { emoji: '4️⃣', label: 'Four', codepoint: '34-20e3', keywords: '4 four number' },
  { emoji: '5️⃣', label: 'Five', codepoint: '35-20e3', keywords: '5 five number' },
  { emoji: '6️⃣', label: 'Six', codepoint: '36-20e3', keywords: '6 six number' },
  { emoji: '7️⃣', label: 'Seven', codepoint: '37-20e3', keywords: '7 seven number' },
  { emoji: '8️⃣', label: 'Eight', codepoint: '38-20e3', keywords: '8 eight number' },
  { emoji: '9️⃣', label: 'Nine', codepoint: '39-20e3', keywords: '9 nine number' },
  { emoji: '🔟', label: 'Ten', codepoint: '1f51f', keywords: '10 ten number' },
  { emoji: '#️⃣', label: 'Hash', codepoint: '23-20e3', keywords: 'hash number pound' },
  { emoji: '*️⃣', label: 'Asterisk', codepoint: '2a-20e3', keywords: 'asterisk number star' },
  { emoji: '🔢', label: 'Input Numbers', codepoint: '1f522', keywords: 'numbers input' },
];

// ══════════════════════════════════════════════════════════════════
// BODY PARTS & PEOPLE
// ══════════════════════════════════════════════════════════════════

const BODY: EmojiEntry[] = [
  { emoji: '👋', label: 'Waving Hand', codepoint: '1f44b', keywords: 'hand wave hello hi' },
  { emoji: '🤚', label: 'Raised Back Hand', codepoint: '1f91a', keywords: 'hand raised' },
  { emoji: '🖐️', label: 'Hand', codepoint: '1f590', keywords: 'hand five fingers' },
  { emoji: '✋', label: 'Raised Hand', codepoint: '270b', keywords: 'hand raised stop' },
  { emoji: '🖖', label: 'Vulcan Salute', codepoint: '1f596', keywords: 'hand vulcan' },
  { emoji: '👌', label: 'OK Hand', codepoint: '1f44c', keywords: 'ok hand perfect' },
  { emoji: '✌️', label: 'Victory', codepoint: '270c', keywords: 'peace victory hand' },
  { emoji: '🤞', label: 'Crossed Fingers', codepoint: '1f91e', keywords: 'fingers crossed luck' },
  { emoji: '🤟', label: 'ILY Hand', codepoint: '1f91f', keywords: 'love hand sign' },
  { emoji: '🤘', label: 'Rock On', codepoint: '1f918', keywords: 'rock on hand' },
  { emoji: '🫰', label: 'Pinch Hand', codepoint: '1faf0', keywords: 'pinch hand money' },
  { emoji: '👍', label: 'Thumbs Up', codepoint: '1f44d', keywords: 'thumbs up good yes like' },
  { emoji: '👎', label: 'Thumbs Down', codepoint: '1f44e', keywords: 'thumbs down no bad' },
  { emoji: '✊', label: 'Raised Fist', codepoint: '270a', keywords: 'fist raised power' },
  { emoji: '👊', label: 'Punch', codepoint: '1f44a', keywords: 'fist bump punch' },
  { emoji: '🤛', label: 'Left Fist', codepoint: '1f91b', keywords: 'fist left' },
  { emoji: '🤜', label: 'Right Fist', codepoint: '1f91c', keywords: 'fist right' },
  { emoji: '👏', label: 'Clap', codepoint: '1f44f', keywords: 'clap hands applause bravo' },
  { emoji: '🙌', label: 'Raising Hands', codepoint: '1f64c', keywords: 'raising hands celebration' },
  { emoji: '🤝', label: 'Handshake', codepoint: '1f91d', keywords: 'handshake deal agree' },
  { emoji: '🙏', label: 'Folded Hands', codepoint: '1f64f', keywords: 'prayer please thank you' },
  { emoji: '💪', label: 'Flexed Bicep', codepoint: '1f4aa', keywords: 'strong muscle flex' },
  { emoji: '👀', label: 'Eyes', codepoint: '1f440', keywords: 'eyes look see' },
  { emoji: '👁️', label: 'Eye', codepoint: '1f441', keywords: 'eye see look' },
  { emoji: '👅', label: 'Tongue', codepoint: '1f445', keywords: 'tongue taste' },
  { emoji: '👄', label: 'Mouth', codepoint: '1f444', keywords: 'mouth lips' },
  { emoji: '👶', label: 'Baby', codepoint: '1f476', keywords: 'baby child' },
  { emoji: '🧒', label: 'Child', codepoint: '1f9d2', keywords: 'child kid' },
  { emoji: '👦', label: 'Boy', codepoint: '1f466', keywords: 'boy child' },
  { emoji: '👧', label: 'Girl', codepoint: '1f467', keywords: 'girl child' },
  { emoji: '🧑', label: 'Person', codepoint: '1f9d1', keywords: 'person adult' },
  { emoji: '👨', label: 'Man', codepoint: '1f468', keywords: 'man father dad' },
  { emoji: '👩', label: 'Woman', codepoint: '1f469', keywords: 'woman mother mom' },
  { emoji: '🧓', label: 'Older Person', codepoint: '1f9d3', keywords: 'elderly grandparent' },
  { emoji: '👴', label: 'Old Man', codepoint: '1f474', keywords: 'old man grandfather' },
  { emoji: '👵', label: 'Old Woman', codepoint: '1f475', keywords: 'old woman grandmother' },
  { emoji: '🧒', label: 'Kid', codepoint: '1f9d2', keywords: 'kid child young' },
];

// ══════════════════════════════════════════════════════════════════
// VEHICLES & TRANSPORT
// ══════════════════════════════════════════════════════════════════

const VEHICLES: EmojiEntry[] = [
  { emoji: '🚗', label: 'Car', codepoint: '1f697', keywords: 'car automobile vehicle' },
  { emoji: '🚕', label: 'Taxi', codepoint: '1f695', keywords: 'taxi cab vehicle' },
  { emoji: '🚌', label: 'Bus', codepoint: '1f68c', keywords: 'bus vehicle' },
  { emoji: '🚎', label: 'Trolleybus', codepoint: '1f68e', keywords: 'bus trolley vehicle' },
  { emoji: '🏎️', label: 'Race Car', codepoint: '1f3ce', keywords: 'race car vehicle fast' },
  { emoji: '🚓', label: 'Police Car', codepoint: '1f693', keywords: 'police car vehicle' },
  { emoji: '🚑', label: 'Ambulance', codepoint: '1f691', keywords: 'ambulance vehicle medical' },
  { emoji: '🚒', label: 'Fire Truck', codepoint: '1f692', keywords: 'fire truck vehicle' },
  { emoji: '🚐', label: 'Minivan', codepoint: '1f690', keywords: 'van minivan vehicle' },
  { emoji: '🛻', label: 'Pickup Truck', codepoint: '1f6fb', keywords: 'truck pickup vehicle' },
  { emoji: '🚚', label: 'Truck', codepoint: '1f69a', keywords: 'truck vehicle delivery' },
  { emoji: '🚛', label: 'Semi Truck', codepoint: '1f69b', keywords: 'truck semi lorry vehicle' },
  { emoji: '🚜', label: 'Tractor', codepoint: '1f69c', keywords: 'tractor farm vehicle' },
  { emoji: '🚲', label: 'Bicycle', codepoint: '1f6b2', keywords: 'bicycle bike cycle vehicle' },
  { emoji: '🛵', label: 'Motor Scooter', codepoint: '1f6f5', keywords: 'scooter moped vehicle' },
  { emoji: '🏍️', label: 'Motorcycle', codepoint: '1f3cd', keywords: 'motorcycle motorbike vehicle' },
  { emoji: '🚂', label: 'Locomotive', codepoint: '1f682', keywords: 'train locomotive vehicle' },
  { emoji: '🚃', label: 'Railway Car', codepoint: '1f683', keywords: 'train car vehicle' },
  { emoji: '🚄', label: 'Bullet Train', codepoint: '1f684', keywords: 'train bullet vehicle fast' },
  { emoji: '✈️', label: 'Airplane', codepoint: '2708', keywords: 'airplane plane aircraft vehicle' },
  { emoji: '🛩️', label: 'Small Plane', codepoint: '1f6e9', keywords: 'airplane small aircraft vehicle' },
  { emoji: '🚀', label: 'Rocket', codepoint: '1f680', keywords: 'rocket space vehicle' },
  { emoji: '🛸', label: 'UFO', codepoint: '1f6f8', keywords: 'ufo alien spacecraft vehicle' },
  { emoji: '⛵', label: 'Sailboat', codepoint: '26f5', keywords: 'sailboat boat ship vehicle' },
  { emoji: '🚤', label: 'Speedboat', codepoint: '1f6a4', keywords: 'speedboat boat vehicle' },
  { emoji: '🛥️', label: 'Motor Boat', codepoint: '1f6e5', keywords: 'boat motor vehicle' },
  { emoji: '🚢', label: 'Ship', codepoint: '1f6a2', keywords: 'ship boat cruise vehicle' },
  { emoji: '🚁', label: 'Helicopter', codepoint: '1f681', keywords: 'helicopter chopper vehicle' },
  { emoji: '🚠', label: 'Mountain Cableway', codepoint: '1f6a0', keywords: 'cable car gondola vehicle' },
  { emoji: '🚟', label: 'Suspension Railway', codepoint: '1f69f', keywords: 'monorail vehicle' },
  { emoji: '🗼', label: 'Tower', codepoint: '1f5fc', keywords: 'tower landmark' },
];

// ══════════════════════════════════════════════════════════════════
// NATURE & WEATHER
// ══════════════════════════════════════════════════════════════════

const NATURE: EmojiEntry[] = [
  { emoji: '🌸', label: 'Cherry Blossom', codepoint: '1f338', keywords: 'flower blossom pink' },
  { emoji: '🌹', label: 'Rose', codepoint: '1f339', keywords: 'flower rose red' },
  { emoji: '🌺', label: 'Hibiscus', codepoint: '1f33a', keywords: 'flower hibiscus' },
  { emoji: '🌻', label: 'Sunflower', codepoint: '1f33b', keywords: 'flower sunflower yellow' },
  { emoji: '🌼', label: 'Blossom', codepoint: '1f33c', keywords: 'flower blossom' },
  { emoji: '🌷', label: 'Tulip', codepoint: '1f337', keywords: 'flower tulip' },
  { emoji: '🌱', label: 'Seedling', codepoint: '1f331', keywords: 'plant seedling sprout' },
  { emoji: '🪴', label: 'Potted Plant', codepoint: '1fab4', keywords: 'plant pot green' },
  { emoji: '🌲', label: 'Evergreen', codepoint: '1f332', keywords: 'tree evergreen pine' },
  { emoji: '🌳', label: 'Deciduous Tree', codepoint: '1f333', keywords: 'tree deciduous' },
  { emoji: '🌴', label: 'Palm Tree', codepoint: '1f334', keywords: 'tree palm tropical' },
  { emoji: '🌵', label: 'Cactus', codepoint: '1f335', keywords: 'cactus desert plant' },
  { emoji: '🌾', label: 'Rice', codepoint: '1f33e', keywords: 'rice grain plant' },
  { emoji: '🌿', label: 'Herb', codepoint: '1f33f', keywords: 'herb leaf plant green' },
  { emoji: '🍀', label: 'Four Leaf Clover', codepoint: '1f340', keywords: 'clover lucky green' },
  { emoji: '🍁', label: 'Maple Leaf', codepoint: '1f341', keywords: 'maple leaf autumn' },
  { emoji: '🍂', label: 'Fallen Leaf', codepoint: '1f342', keywords: 'leaf fall autumn' },
  { emoji: '🍃', label: 'Leaf', codepoint: '1f343', keywords: 'leaf wind green' },
  { emoji: '🪹', label: 'Empty Nest', codepoint: '1fab9', keywords: 'nest bird' },
  { emoji: '🪺', label: 'Nest with Eggs', codepoint: '1faba', keywords: 'nest eggs bird' },
  { emoji: '☀️', label: 'Sun', codepoint: '2600', keywords: 'sun sunny weather' },
  { emoji: '🌤️', label: 'Mostly Sunny', codepoint: '1f324', keywords: 'sun weather' },
  { emoji: '⛅', label: 'Partly Cloudy', codepoint: '26c5', keywords: 'sun cloud weather' },
  { emoji: '🌥️', label: 'Mostly Cloudy', codepoint: '1f325', keywords: 'cloud weather' },
  { emoji: '☁️', label: 'Cloud', codepoint: '2601', keywords: 'cloud weather' },
  { emoji: '🌦️', label: 'Sun Rain', codepoint: '1f326', keywords: 'sun rain weather' },
  { emoji: '🌧️', label: 'Rain', codepoint: '1f327', keywords: 'rain cloud weather' },
  { emoji: '⛈️', label: 'Thunderstorm', codepoint: '26c8', keywords: 'thunder storm weather' },
  { emoji: '❄️', label: 'Snow', codepoint: '2744', keywords: 'snow winter weather cold' },
  { emoji: '🌸', label: 'Blossom', codepoint: '1f338', keywords: 'flower blossom spring' },
];

// ══════════════════════════════════════════════════════════════════
// OBJECTS & TOYS
// ══════════════════════════════════════════════════════════════════

const OBJECTS: EmojiEntry[] = [
  { emoji: '⚽', label: 'Soccer Ball', codepoint: '26bd', keywords: 'ball soccer football sport' },
  { emoji: '🏀', label: 'Basketball', codepoint: '1f3c0', keywords: 'ball basketball sport' },
  { emoji: '🏈', label: 'Football', codepoint: '1f3c8', keywords: 'ball football american sport' },
  { emoji: '⚾', label: 'Baseball', codepoint: '26be', keywords: 'ball baseball sport' },
  { emoji: '🎾', label: 'Tennis', codepoint: '1f3be', keywords: 'ball tennis sport' },
  { emoji: '🏐', label: 'Volleyball', codepoint: '1f3d0', keywords: 'ball volleyball sport' },
  { emoji: '🏉', label: 'Rugby', codepoint: '1f3c9', keywords: 'ball rugby sport' },
  { emoji: '🎱', label: '8 Ball', codepoint: '1f3b1', keywords: 'billiards pool ball game' },
  { emoji: '🪀', label: 'Yo-Yo', codepoint: '1fa80', keywords: 'yo-yo toy game' },
  { emoji: '🪁', label: 'Kite', codepoint: '1fa81', keywords: 'kite toy fly' },
  { emoji: '🎮', label: 'Game Controller', codepoint: '1f3ae', keywords: 'game controller video game play' },
  { emoji: '🕹️', label: 'Joystick', codepoint: '1f579', keywords: 'joystick game arcade' },
  { emoji: '🎲', label: 'Dice', codepoint: '1f3b2', keywords: 'dice game random' },
  { emoji: '🧩', label: 'Puzzle', codepoint: '1f9e9', keywords: 'puzzle jigsaw piece game' },
  { emoji: '🎯', label: 'Target', codepoint: '1f3af', keywords: 'target bullseye dart game' },
  { emoji: '🎪', label: 'Circus', codepoint: '1f3aa', keywords: 'circus tent' },
  { emoji: '🎨', label: 'Art Palette', codepoint: '1f3a8', keywords: 'art paint palette color' },
  { emoji: '🎭', label: 'Performing Arts', codepoint: '1f3ad', keywords: 'theater drama mask' },
  { emoji: '🎬', label: 'Clapper Board', codepoint: '1f3ac', keywords: 'movie film clapper' },
  { emoji: '🎤', label: 'Microphone', codepoint: '1f3a4', keywords: 'microphone mic sing karaoke' },
  { emoji: '🎧', label: 'Headphones', codepoint: '1f3a7', keywords: 'headphones earphone music' },
  { emoji: '🎵', label: 'Music Note', codepoint: '1f3b5', keywords: 'music note song' },
  { emoji: '🎶', label: 'Music Notes', codepoint: '1f3b6', keywords: 'music notes song melody' },
  { emoji: '🎹', label: 'Piano', codepoint: '1f3b9', keywords: 'piano keyboard music' },
  { emoji: '🎸', label: 'Guitar', codepoint: '1f3b8', keywords: 'guitar music instrument' },
  { emoji: '🎺', label: 'Trumpet', codepoint: '1f3ba', keywords: 'trumpet music instrument' },
  { emoji: '🎻', label: 'Violin', codepoint: '1f3bb', keywords: 'violin music instrument' },
  { emoji: '📖', label: 'Open Book', codepoint: '1f4d6', keywords: 'book read story' },
  { emoji: '📚', label: 'Books', codepoint: '1f4da', keywords: 'books stack read study' },
  { emoji: '✏️', label: 'Pencil', codepoint: '270f', keywords: 'pencil write draw' },
  { emoji: '🖍️', label: 'Crayon', codepoint: '1f58d', keywords: 'crayon color draw' },
  { emoji: '📝', label: 'Memo', codepoint: '1f4dd', keywords: 'memo note write' },
  { emoji: '📌', label: 'Pushpin', codepoint: '1f4cc', keywords: 'pin pushpin' },
  { emoji: '📎', label: 'Paperclip', codepoint: '1f4ce', keywords: 'paperclip clip' },
  { emoji: '🔍', label: 'Magnifier', codepoint: '1f50d', keywords: 'search magnifier look' },
  { emoji: '🔑', label: 'Key', codepoint: '1f511', keywords: 'key lock' },
  { emoji: '🧲', label: 'Magnet', codepoint: '1f9f2', keywords: 'magnet magnetic' },
  { emoji: '🎁', label: 'Gift', codepoint: '1f381', keywords: 'gift present box surprise' },
  { emoji: '🎈', label: 'Balloon', codepoint: '1f388', keywords: 'balloon party' },
  { emoji: '🎉', label: 'Party Popper', codepoint: '1f389', keywords: 'party popper celebrate confetti' },
  { emoji: '🎊', label: 'Confetti Ball', codepoint: '1f38a', keywords: 'confetti ball celebrate' },
  { emoji: '🎗️', label: 'Ribbon', codepoint: '1f397', keywords: 'ribbon reminder' },
  { emoji: '🏆', label: 'Trophy', codepoint: '1f3c6', keywords: 'trophy winner award' },
  { emoji: '🥇', label: 'Gold Medal', codepoint: '1f947', keywords: 'medal gold first place winner' },
  { emoji: '🥈', label: 'Silver Medal', codepoint: '1f948', keywords: 'medal silver second' },
  { emoji: '🥉', label: 'Bronze Medal', codepoint: '1f949', keywords: 'medal bronze third' },
  { emoji: '🏅', label: 'Sports Medal', codepoint: '1f3c5', keywords: 'medal sports winner' },
  { emoji: '🪅', label: 'Piñata', codepoint: '1fa85', keywords: 'pinata party toy' },
  { emoji: '🧸', label: 'Teddy Bear', codepoint: '1f9f8', keywords: 'teddy bear toy stuffed' },
  { emoji: '🪆', label: 'Nesting Dolls', codepoint: '1fa86', keywords: 'doll matryoshka toy' },
  { emoji: '🎎', label: 'Doll', codepoint: '1f38e', keywords: 'doll toy' },
  { emoji: '🎪', label: 'Circus Tent', codepoint: '1f3aa', keywords: 'circus tent show' },
  { emoji: '🪄', label: 'Magic Wand', codepoint: '1fa84', keywords: 'magic wand wizard' },
  { emoji: '🔮', label: 'Crystal Ball', codepoint: '1f52e', keywords: 'crystal ball magic fortune' },
  { emoji: '🧸', label: 'Teddy', codepoint: '1f9f8', keywords: 'teddy bear toy' },
];

// ══════════════════════════════════════════════════════════════════
// EMOTIONS & FACES
// ══════════════════════════════════════════════════════════════════

const FACES: EmojiEntry[] = [
  { emoji: '😀', label: 'Grinning', codepoint: '1f600', keywords: 'happy smile face' },
  { emoji: '😃', label: 'Smiley', codepoint: '1f603', keywords: 'happy smile face' },
  { emoji: '😄', label: 'Smile', codepoint: '1f604', keywords: 'happy smile eyes face' },
  { emoji: '😁', label: 'Grin', codepoint: '1f601', keywords: 'grin happy face' },
  { emoji: '😆', label: 'Laughing', codepoint: '1f606', keywords: 'laughing happy face' },
  { emoji: '😅', label: 'Sweat Smile', codepoint: '1f605', keywords: 'sweat smile nervous face' },
  { emoji: '🤣', label: 'Rolling Laugh', codepoint: '1f923', keywords: 'laughing rolling face' },
  { emoji: '😂', label: 'Joy Tears', codepoint: '1f602', keywords: 'cry laugh happy face' },
  { emoji: '🙂', label: 'Slight Smile', codepoint: '1f642', keywords: 'smile face' },
  { emoji: '😊', label: 'Blush', codepoint: '1f60a', keywords: 'blush happy smile face' },
  { emoji: '😇', label: 'Halo', codepoint: '1f607', keywords: 'angel halo good face' },
  { emoji: '🥰', label: 'Hearts Face', codepoint: '1f970', keywords: 'love heart face' },
  { emoji: '😍', label: 'Heart Eyes', codepoint: '1f60d', keywords: 'love heart eyes face' },
  { emoji: '🤩', label: 'Star Struck', codepoint: '1f929', keywords: 'star eyes excited face' },
  { emoji: '😘', label: 'Kiss', codepoint: '1f618', keywords: 'kiss love face' },
  { emoji: '😗', label: 'Kissing', codepoint: '1f617', keywords: 'kiss face' },
  { emoji: '😚', label: 'Closed Kiss', codepoint: '1f61a', keywords: 'kiss closed eyes face' },
  { emoji: '😙', label: 'Kiss Smile', codepoint: '1f619', keywords: 'kiss smile face' },
  { emoji: '🥲', label: 'Smile Tear', codepoint: '1f972', keywords: 'smile tear happy sad face' },
  { emoji: '😋', label: 'Yum', codepoint: '1f60b', keywords: 'yum delicious face' },
  { emoji: '😛', label: 'Tongue Out', codepoint: '1f61b', keywords: 'tongue out silly face' },
  { emoji: '😜', label: 'Wink Tongue', codepoint: '1f61c', keywords: 'wink tongue silly face' },
  { emoji: '🤪', label: 'Zany', codepoint: '1f92a', keywords: 'crazy zany silly face' },
  { emoji: '😝', label: 'Squint Tongue', codepoint: '1f61d', keywords: 'squint tongue face' },
  { emoji: '🤑', label: 'Money Face', codepoint: '1f911', keywords: 'money face rich' },
  { emoji: '🤗', label: 'Hug', codepoint: '1f917', keywords: 'hug hug face' },
  { emoji: '🤭', label: 'Oops', codepoint: '1f92d', keywords: 'oops giggle face' },
  { emoji: '🫢', label: 'Surprise', codepoint: '1fae2', keywords: 'surprise gasp face' },
  { emoji: '🤫', label: 'Shh', codepoint: '1f92b', keywords: 'quiet shh secret face' },
  { emoji: '🤔', label: 'Thinking', codepoint: '1f914', keywords: 'thinking hmm face' },
  { emoji: '🫡', label: 'Salute', codepoint: '1fae1', keywords: 'salute respect face' },
  { emoji: '🤐', label: 'Zipper', codepoint: '1f910', keywords: 'zipper mouth quiet face' },
  { emoji: '🤨', label: 'Raised Eyebrow', codepoint: '1f928', keywords: 'raised eyebrow skeptical face' },
  { emoji: '😐', label: 'Neutral', codepoint: '1f610', keywords: 'neutral face' },
  { emoji: '😑', label: 'Expressionless', codepoint: '1f611', keywords: 'expressionless face' },
  { emoji: '😶', label: 'No Mouth', codepoint: '1f636', keywords: 'no mouth silent face' },
  { emoji: '😏', label: 'Smirk', codepoint: '1f60f', keywords: 'smirk face' },
  { emoji: '😒', label: 'Unamused', codepoint: '1f612', keywords: 'unamused annoyed face' },
  { emoji: '🙄', label: 'Eye Roll', codepoint: '1f644', keywords: 'eye roll face' },
  { emoji: '😬', label: 'Grimace', codepoint: '1f62c', keywords: 'grimace awkward face' },
  { emoji: '🤥', label: 'Lying', codepoint: '1f925', keywords: 'lying nose face' },
  { emoji: '🫠', label: 'Melting', codepoint: '1fae0', keywords: 'melting hot face' },
  { emoji: '😌', label: 'Relieved', codepoint: '1f60c', keywords: 'relieved calm face' },
  { emoji: '😔', label: 'Pensive', codepoint: '1f614', keywords: 'pensive sad face' },
  { emoji: '😪', label: 'Sleepy', codepoint: '1f62a', keywords: 'sleepy tired face' },
  { emoji: '🤤', label: 'Drooling', codepoint: '1f924', keywords: 'drooling face' },
  { emoji: '😴', label: 'Sleeping', codepoint: '1f634', keywords: 'sleeping zzz face' },
  { emoji: '😷', label: 'Mask', codepoint: '1f637', keywords: 'mask sick face' },
  { emoji: '🤒', label: 'Thermometer', codepoint: '1f912', keywords: 'sick thermometer face' },
  { emoji: '🤕', label: 'Bandaged', codepoint: '1f915', keywords: 'hurt bandage face' },
  { emoji: '🤢', label: 'Nauseous', codepoint: '1f922', keywords: 'sick vomit face' },
  { emoji: '🤮', label: 'Vomiting', codepoint: '1f92e', keywords: 'vomit sick face' },
  { emoji: '🥵', label: 'Hot Face', codepoint: '1f975', keywords: 'hot sweating face' },
  { emoji: '🥶', label: 'Cold Face', codepoint: '1f976', keywords: 'cold freezing face' },
  { emoji: '🥴', label: 'Woozy', codepoint: '1f974', keywords: 'woozy dizzy face' },
  { emoji: '😵', label: 'Dizzy', codepoint: '1f635', keywords: 'dizzy face' },
  { emoji: '🤯', label: 'Mind Blown', codepoint: '1f92f', keywords: 'mind blown shocked face' },
  { emoji: '🤠', label: 'Cowboy', codepoint: '1f920', keywords: 'cowboy hat face' },
  { emoji: '🥳', label: 'Party', codepoint: '1f973', keywords: 'party celebrate face' },
  { emoji: '🥸', label: 'Disguise', codepoint: '1f978', keywords: 'disguise face' },
  { emoji: '😎', label: 'Cool', codepoint: '1f60e', keywords: 'cool sunglasses face' },
  { emoji: '🤓', label: 'Nerd', codepoint: '1f913', keywords: 'nerd glasses face' },
  { emoji: '🧐', label: 'Monocle', codepoint: '1f9d0', keywords: 'monocle face' },
  { emoji: '😕', label: 'Confused', codepoint: '1f615', keywords: 'confused face' },
  { emoji: '🫤', label: 'Diagonal Mouth', codepoint: '1fae4', keywords: 'confused mouth face' },
  { emoji: '😟', label: 'Worried', codepoint: '1f61f', keywords: 'worried face' },
  { emoji: '🙁', label: 'Slight Frown', codepoint: '1f641', keywords: 'frown sad face' },
  { emoji: '😮', label: 'Surprised', codepoint: '1f62e', keywords: 'surprised wow face' },
  { emoji: '😯', label: 'Hushed', codepoint: '1f62f', keywords: 'hushed surprised face' },
  { emoji: '😲', label: 'Astonished', codepoint: '1f632', keywords: 'astonished shocked face' },
  { emoji: '😳', label: 'Flushed', codepoint: '1f633', keywords: 'flushed embarrassed face' },
  { emoji: '🥺', label: 'Pleading', codepoint: '1f97a', keywords: 'pleading puppy eyes sad face' },
  { emoji: '🥹', label: 'Holding Back Tears', codepoint: '1f979', keywords: 'holding tears emotional face' },
  { emoji: '😦', label: 'Frown Open', codepoint: '1f626', keywords: 'frown open mouth face' },
  { emoji: '😧', label: 'Anguished', codepoint: '1f627', keywords: 'anguished face' },
  { emoji: '😨', label: 'Fearful', codepoint: '1f628', keywords: 'fearful scared face' },
  { emoji: '😰', label: 'Cold Sweat', codepoint: '1f630', keywords: 'cold sweat nervous face' },
  { emoji: '😢', label: 'Crying', codepoint: '1f622', keywords: 'crying sad tear face' },
  { emoji: '😭', label: 'Loud Cry', codepoint: '1f62d', keywords: 'crying loud sad face' },
  { emoji: '😱', label: 'Scream', codepoint: '1f631', keywords: 'scream scared face' },
  { emoji: '😖', label: 'Confounded', codepoint: '1f616', keywords: 'confounded face' },
  { emoji: '😣', label: 'Persevere', codepoint: '1f623', keywords: 'persevere struggling face' },
  { emoji: '😞', label: 'Disappointed', codepoint: '1f61e', keywords: 'disappointed sad face' },
  { emoji: '😓', label: 'Down Sweat', codepoint: '1f613', keywords: 'sweat sad face' },
  { emoji: '😩', label: 'Weary', codepoint: '1f629', keywords: 'weary tired face' },
  { emoji: '😫', label: 'Tired', codepoint: '1f62b', keywords: 'tired face' },
  { emoji: '🥱', label: 'Yawn', codepoint: '1f971', keywords: 'yawn tired sleepy face' },
  { emoji: '😤', label: 'Huff', codepoint: '1f624', keywords: 'angry huff face' },
  { emoji: '😡', label: 'Angry', codepoint: '1f621', keywords: 'angry red face' },
  { emoji: '🤬', label: 'Swearing', codepoint: '1f92c', keywords: 'angry swearing face' },
  { emoji: '😈', label: 'Devil', codepoint: '1f608', keywords: 'devil evil smile' },
  { emoji: '👿', label: 'Angry Devil', codepoint: '1f47f', keywords: 'devil angry imp' },
  { emoji: '💀', label: 'Skull', codepoint: '1f480', keywords: 'skull dead' },
  { emoji: '👻', label: 'Ghost', codepoint: '1f47b', keywords: 'ghost halloween spooky' },
  { emoji: '👽', label: 'Alien', codepoint: '1f47d', keywords: 'alien ufo space' },
  { emoji: '🤖', label: 'Robot', codepoint: '1f916', keywords: 'robot face bot' },
  { emoji: '🤡', label: 'Clown', codepoint: '1f921', keywords: 'clown face' },
  { emoji: '💩', label: 'Pile of Poo', codepoint: '1f4a9', keywords: 'poo poop face' },
  { emoji: '😺', label: 'Happy Cat', codepoint: '1f63a', keywords: 'cat happy face' },
  { emoji: '😸', label: 'Grin Cat', codepoint: '1f638', keywords: 'cat grin face' },
  { emoji: '😹', label: 'Joy Cat', codepoint: '1f639', keywords: 'cat joy laugh face' },
  { emoji: '😻', label: 'Heart Cat', codepoint: '1f63b', keywords: 'cat heart love face' },
  { emoji: '😼', label: 'Smirk Cat', codepoint: '1f63c', keywords: 'cat smirk face' },
  { emoji: '😽', label: 'Kiss Cat', codepoint: '1f63d', keywords: 'cat kiss face' },
  { emoji: '🙀', label: 'Weary Cat', codepoint: '1f640', keywords: 'cat weary surprised face' },
  { emoji: '😿', label: 'Crying Cat', codepoint: '1f63f', keywords: 'cat cry sad face' },
  { emoji: '😾', label: 'Pouting Cat', codepoint: '1f63e', keywords: 'cat angry pout face' },
];

// ══════════════════════════════════════════════════════════════════
// BUILDINGS & PLACES
// ══════════════════════════════════════════════════════════════════

const PLACES: EmojiEntry[] = [
  { emoji: '🏠', label: 'House', codepoint: '1f3e0', keywords: 'house home building' },
  { emoji: '🏡', label: 'House with Garden', codepoint: '1f3e1', keywords: 'house garden home' },
  { emoji: '🏫', label: 'School', codepoint: '1f3eb', keywords: 'school building' },
  { emoji: '🏬', label: 'Department Store', codepoint: '1f3ec', keywords: 'store building' },
  { emoji: '🏭', label: 'Factory', codepoint: '1f3ed', keywords: 'factory building' },
  { emoji: '🏯', label: 'Japanese Castle', codepoint: '1f3ef', keywords: 'castle building' },
  { emoji: '🏰', label: 'Castle', codepoint: '1f3f0', keywords: 'castle building' },
  { emoji: '💒', label: 'Church', codepoint: '1f492', keywords: 'church wedding building' },
  { emoji: '🗼', label: 'Tokyo Tower', codepoint: '1f5fc', keywords: 'tower tokyo building' },
  { emoji: '🗽', label: 'Statue of Liberty', codepoint: '1f5fd', keywords: 'liberty statue building' },
  { emoji: '⛪', label: 'Church', codepoint: '26ea', keywords: 'church building' },
  { emoji: '🕌', label: 'Mosque', codepoint: '1f54c', keywords: 'mosque building' },
  { emoji: '⛩️', label: 'Shrine', codepoint: '26e9', keywords: 'shrine building' },
  { emoji: '🎠', label: 'Carousel', codepoint: '1f3a0', keywords: 'carousel horse ride park' },
  { emoji: '🛝', label: 'Slide', codepoint: '1f6dd', keywords: 'slide playground park' },
  { emoji: '🎡', label: 'Ferris Wheel', codepoint: '1f3a1', keywords: 'ferris wheel ride park' },
  { emoji: '🎢', label: 'Roller Coaster', codepoint: '1f3a2', keywords: 'roller coaster ride park' },
  { emoji: '⛱️', label: 'Beach Umbrella', codepoint: '26f1', keywords: 'beach umbrella sun' },
  { emoji: '🏖️', label: 'Beach', codepoint: '1f3d6', keywords: 'beach ocean sand' },
  { emoji: '🏕️', label: 'Camping', codepoint: '1f3d5', keywords: 'camping tent outdoor' },
  { emoji: '⛰️', label: 'Mountain', codepoint: '26f0', keywords: 'mountain outdoor' },
  { emoji: '🏔️', label: 'Snow Mountain', codepoint: '1f3d4', keywords: 'mountain snow winter' },
  { emoji: '🌋', label: 'Volcano', codepoint: '1f30b', keywords: 'volcano mountain' },
  { emoji: '🏝️', label: 'Desert Island', codepoint: '1f3dd', keywords: 'island tropical desert' },
  { emoji: '🌌', label: 'Milky Way', codepoint: '1f30c', keywords: 'milky way space night' },
];

// ══════════════════════════════════════════════════════════════════
// FLAGS & MARKS
// ══════════════════════════════════════════════════════════════════

const MARKS: EmojiEntry[] = [
  { emoji: '✅', label: 'Check', codepoint: '2705', keywords: 'check correct yes done' },
  { emoji: '❌', label: 'Cross', codepoint: '274c', keywords: 'cross no wrong error' },
  { emoji: '❓', label: 'Question', codepoint: '2753', keywords: 'question mark' },
  { emoji: '❗', label: 'Exclamation', codepoint: '2757', keywords: 'exclamation mark important' },
  { emoji: '‼️', label: 'Double Exclamation', codepoint: '203c', keywords: 'exclamation important' },
  { emoji: '⁉️', label: 'Excl Question', codepoint: '2049', keywords: 'question exclamation' },
  { emoji: '💤', label: 'Zzz', codepoint: '1f4a4', keywords: 'zzz sleep tired' },
  { emoji: '💬', label: 'Speech Bubble', codepoint: '1f4ac', keywords: 'speech bubble chat' },
  { emoji: '💭', label: 'Thought Bubble', codepoint: '1f4ad', keywords: 'thought bubble think' },
  { emoji: '🗯️', label: 'Anger Bubble', codepoint: '1f5ef', keywords: 'anger bubble shout' },
  { emoji: '🕐', label: 'One O Clock', codepoint: '1f550', keywords: 'clock time' },
  { emoji: '⏰', label: 'Alarm Clock', codepoint: '23f0', keywords: 'alarm clock time' },
  { emoji: '⏳', label: 'Hourglass', codepoint: '23f3', keywords: 'hourglass time wait' },
  { emoji: '⌛', label: 'Hourglass Done', codepoint: '231b', keywords: 'hourglass done time' },
  { emoji: '🧭', label: 'Compass', codepoint: '1f9ed', keywords: 'compass direction' },
  { emoji: '📍', label: 'Pin', codepoint: '1f4cd', keywords: 'pin location map' },
  { emoji: '🚩', label: 'Flag', codepoint: '1f6a9', keywords: 'flag red' },
  { emoji: '🏳️', label: 'White Flag', codepoint: '1f3f3', keywords: 'flag white peace' },
  { emoji: '🏴', label: 'Black Flag', codepoint: '1f3f4', keywords: 'flag black' },
  { emoji: '🏳️‍🌈', label: 'Rainbow Flag', codepoint: '1f3f3-fe0f-200d-1f308', keywords: 'flag rainbow pride' },
  { emoji: '🏳️‍⚧️', label: 'Trans Flag', codepoint: '1f3f3-fe0f-200d-26a7-fe0f', keywords: 'flag transgender' },
  { emoji: '🏴‍☠️', label: 'Pirate Flag', codepoint: '1f3f4-200d-2620-fe0f', keywords: 'flag pirate' },
  { emoji: '®️', label: 'Registered', keywords: 'registered trademark' },
  { emoji: '©️', label: 'Copyright', keywords: 'copyright' },
  { emoji: '™️', label: 'Trademark', codepoint: '2122', keywords: 'trademark' },
  { emoji: '♈', label: 'Aries', codepoint: '2648', keywords: 'aries zodiac' },
  { emoji: '♉', label: 'Taurus', codepoint: '2649', keywords: 'taurus zodiac' },
  { emoji: '♊', label: 'Gemini', codepoint: '264a', keywords: 'gemini zodiac' },
  { emoji: '♋', label: 'Cancer', codepoint: '264b', keywords: 'cancer zodiac' },
  { emoji: '♌', label: 'Leo', codepoint: '264c', keywords: 'leo zodiac' },
  { emoji: '♍', label: 'Virgo', codepoint: '264d', keywords: 'virgo zodiac' },
  { emoji: '♎', label: 'Libra', codepoint: '264e', keywords: 'libra zodiac' },
  { emoji: '♏', label: 'Scorpio', codepoint: '264f', keywords: 'scorpio zodiac' },
  { emoji: '♐', label: 'Sagittarius', codepoint: '2650', keywords: 'sagittarius zodiac' },
  { emoji: '♑', label: 'Capricorn', codepoint: '2651', keywords: 'capricorn zodiac' },
  { emoji: '♒', label: 'Aquarius', codepoint: '2652', keywords: 'aquarius zodiac' },
  { emoji: '♓', label: 'Pisces', codepoint: '2653', keywords: 'pisces zodiac' },
];

// ══════════════════════════════════════════════════════════════════
// CLOTHING & ACCESSORIES
// ══════════════════════════════════════════════════════════════════

const CLOTHING: EmojiEntry[] = [
  { emoji: '👓', label: 'Glasses', codepoint: '1f453', keywords: 'glasses spectacles' },
  { emoji: '🕶️', label: 'Sunglasses', codepoint: '1f576', keywords: 'sunglasses cool' },
  { emoji: '🥽', label: 'Goggles', codepoint: '1f97d', keywords: 'goggles swim' },
  { emoji: '👒', label: 'Hat', codepoint: '1f452', keywords: 'hat sun hat' },
  { emoji: '🎓', label: 'Graduation', codepoint: '1f393', keywords: 'graduation cap school' },
  { emoji: '🧢', label: 'Cap', codepoint: '1f9e2', keywords: 'cap hat baseball' },
  { emoji: '👑', label: 'Crown', codepoint: '1f451', keywords: 'crown king queen' },
  { emoji: '💍', label: 'Ring', codepoint: '1f48d', keywords: 'ring jewelry' },
  { emoji: '👜', label: 'Handbag', codepoint: '1f45c', keywords: 'handbag bag purse' },
  { emoji: '🎒', label: 'Backpack', codepoint: '1f392', keywords: 'backpack school bag' },
  { emoji: '🧣', label: 'Scarf', codepoint: '1f9e3', keywords: 'scarf winter' },
  { emoji: '🧤', label: 'Gloves', codepoint: '1f9e4', keywords: 'gloves winter' },
  { emoji: '🧥', label: 'Coat', codepoint: '1f9e5', keywords: 'coat jacket' },
  { emoji: '👗', label: 'Dress', codepoint: '1f457', keywords: 'dress' },
  { emoji: '👘', label: 'Kimono', codepoint: '1f458', keywords: 'kimono' },
  { emoji: '👙', label: 'Bikini', codepoint: '1f459', keywords: 'bikini swim' },
  { emoji: '👚', label: 'Blouse', codepoint: '1f45a', keywords: 'blouse shirt' },
  { emoji: '👕', label: 'Shirt', codepoint: '1f455', keywords: 'shirt t-shirt' },
  { emoji: '👖', label: 'Jeans', codepoint: '1f456', keywords: 'jeans pants trousers' },
  { emoji: '👔', label: 'Necktie', codepoint: '1f454', keywords: 'tie necktie formal' },
  { emoji: '👞', label: 'Shoe', codepoint: '1f45e', keywords: 'shoe footwear' },
  { emoji: '👟', label: 'Sneaker', codepoint: '1f45f', keywords: 'sneaker shoe sport' },
  { emoji: '🥾', label: 'Hiking Boot', codepoint: '1f97e', keywords: 'boot hiking' },
  { emoji: '🥿', label: 'Flat Shoe', codepoint: '1f97f', keywords: 'shoe flat' },
  { emoji: '👠', label: 'High Heel', codepoint: '1f460', keywords: 'heel shoe high' },
  { emoji: '👡', label: 'Sandal', codepoint: '1f461', keywords: 'sandal shoe' },
  { emoji: '👢', label: 'Boot', codepoint: '1f462', keywords: 'boot shoe' },
  { emoji: '🩴', label: 'Flip Flop', codepoint: '1fa74', keywords: 'flip flop sandal shoe' },
];

// ══════════════════════════════════════════════════════════════════
// ASSEMBLY
// ══════════════════════════════════════════════════════════════════

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  { id: 'faces',   label: 'Smileys', icon: '😀', emojis: FACES },
  { id: 'animals', label: 'Animals', icon: '🐶', emojis: ANIMALS },
  { id: 'food',    label: 'Food',    icon: '🍎', emojis: FOOD },
  { id: 'objects', label: 'Objects', icon: '⚽', emojis: OBJECTS },
  { id: 'body',    label: 'People',  icon: '👋', emojis: BODY },
  { id: 'shapes',  label: 'Shapes',  icon: '⭐', emojis: SHAPES },
  { id: 'nature',  label: 'Nature',  icon: '🌸', emojis: NATURE },
  { id: 'vehicles',label: 'Travel',  icon: '🚗', emojis: VEHICLES },
  { id: 'places',  label: 'Places',  icon: '🏠', emojis: PLACES },
  { id: 'clothing',label: 'Clothes', icon: '👗', emojis: CLOTHING },
  { id: 'numbers', label: 'Numbers', icon: '🔢', emojis: NUMBERS },
  { id: 'marks',   label: 'Marks',   icon: '✅', emojis: MARKS },
];

/** Flat search across all categories */
export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  const results: EmojiEntry[] = [];
  const seen = new Set<string>();
  for (const cat of EMOJI_CATEGORIES) {
    for (const e of cat.emojis) {
      if (seen.has(e.emoji)) continue;
      if (
        e.label.toLowerCase().includes(q) ||
        e.keywords.toLowerCase().includes(q)
      ) {
        results.push(e);
        seen.add(e.emoji);
      }
    }
  }
  return results;
}
